"""
Django settings for smartsales_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import stripe
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-m0#4q)g=9b_ne2tl8-*=b$@%vzs7)wg@_s8vfie0a4o$o!h4i4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Configurar ALLOWED_HOSTS para producción
ALLOWED_HOSTS_STRING = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1')
ALLOWED_HOSTS = ALLOWED_HOSTS_STRING.split(' ') if ALLOWED_HOSTS_STRING else []

# Render inyecta la URL del servicio en RENDER_EXTERNAL_HOSTNAME
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Google Cloud Run inyecta el hostname en K_SERVICE
CLOUD_RUN_SERVICE_URL = os.environ.get('K_SERVICE')
if CLOUD_RUN_SERVICE_URL:
    # Cloud Run URLs son *.run.app
    ALLOWED_HOSTS.append('.run.app')
    ALLOWED_HOSTS.append('*')  # Para dominios custom


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'cloudinary_storage',
    'cloudinary',
    'django_cleanup.apps.CleanupConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    # Local apps
    'users',
    'products',
    'orders',
    'analytics',
    'reports',
    'notifications',  # Sistema de notificaciones
    'offers',  # Sistema de ofertas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartsales_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartsales_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Usar dj-database-url para configurar desde DATABASE_URL (Render la inyecta)
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'postgresql://postgres:admin123@localhost:5432/smartsales_db'),
        conn_max_age=600,  # Reutilizar conexiones
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración para Whitenoise y Cloudinary (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Spectacular Settings (Swagger/OpenAPI)
SPECTACULAR_SETTINGS = {
    'TITLE': 'SmartSales365 API',
    'DESCRIPTION': 'API para el sistema de gestión de ventas SmartSales365',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',   # Puerto estándar de React
    'http://localhost:3039',   # Puerto de desarrollo actual
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3039',
]

# Permite todos los headers y métodos para CORS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 🔧 Exponer headers para descarga de archivos
CORS_EXPOSE_HEADERS = [
    'content-disposition',
    'content-type',
    'content-length',
]

CORS_ALLOW_CREDENTIALS = True

# Security Settings for Production
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'True') == 'True'
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'True') == 'True'
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True'

# Configurar HSTS si tu dominio lo soporta (descomenta en producción)
# SECURE_HSTS_SECONDS = 31536000  # 1 año
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
FRONTEND_CHECKOUT_SUCCESS_URL = os.environ.get('FRONTEND_CHECKOUT_SUCCESS_URL', 'http://localhost:3000/checkout/success?session_id={CHECKOUT_SESSION_ID}')
FRONTEND_CHECKOUT_CANCEL_URL = os.environ.get('FRONTEND_CHECKOUT_CANCEL_URL', 'http://localhost:3000/checkout/cancel')

# Configurar Stripe API key globalmente
stripe.api_key = STRIPE_SECRET_KEY

# Google AI Configuration
GOOGLE_AI_API_KEY = os.environ.get('GOOGLE_AI_API_KEY', '')

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# =============================================================================
# MAPEO DE CATEGORÍAS COMPLEMENTARIAS PARA SISTEMA DE RECOMENDACIONES
# =============================================================================
# Define qué categorías de productos se recomiendan juntas.
# Formato: 'Categoría Origen': ['Categoría Complementaria 1', 'Categoría Complementaria 2', ...]
# Lógica de negocio: Si un cliente ve/compra un producto de la categoría origen,
# se le recomiendan productos populares de las categorías complementarias.

COMPLEMENTARY_CATEGORIES = {
    # Entretenimiento en el hogar
    'Televisores': ['Audio', 'Computación'],  # TV + Audio/Streaming devices
    'Audio': ['Televisores', 'Computación'],  # Sistemas de audio + TV/PC
    
    # Cocina y alimentación
    'Cocción': ['Refrigeración', 'Pequeños Electrodomésticos Cocina', 'Preparación de Alimentos', 'Microondas'],
    'Refrigeración': ['Cocción', 'Pequeños Electrodomésticos Cocina', 'Preparación de Alimentos'],
    'Refrigeradores': ['Cocción', 'Microondas', 'Pequeños Electrodomésticos Cocina'],
    'Microondas': ['Refrigeración', 'Refrigeradores', 'Pequeños Electrodomésticos Cocina'],
    'Pequeños Electrodomésticos Cocina': ['Preparación de Alimentos', 'Cocción', 'Microondas'],
    'Preparación de Alimentos': ['Pequeños Electrodomésticos Cocina', 'Cocción'],
    
    # Lavado y limpieza
    'Lavado y Secado': ['Limpieza del Hogar', 'Lavadoras'],  # Lavadora + aspiradora/plancha
    'Lavadoras': ['Lavado y Secado', 'Limpieza del Hogar'],
    'Limpieza del Hogar': ['Lavado y Secado', 'Lavadoras'],
    
    # Tecnología
    'Computación': ['Computación', 'Audio'],  # Laptop -> Monitor/Teclado/Mouse o Auriculares
    
    # Confort
    'Climatización': ['Climatización'],  # Aire acondicionado + ventiladores/calefactores
    'Cuidado Personal': ['Cuidado Personal', 'Limpieza del Hogar'],  # Afeitadoras + secadores
}

# =============================================================================
# FIREBASE CONFIGURATION - Push Notifications
# =============================================================================
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'smartsales-firebase-key.json')
FIREBASE_WEB_PUSH_CERTIFICATE = os.environ.get(
    'FIREBASE_WEB_PUSH_CERTIFICATE',
    '7rVPMZoay6m1vIC8k61PaqIu5vL_cSSxm_04t2GxepQ'  # VAPID Key
)

# Inicializar Firebase Admin SDK
try:
    import firebase_admin
    from firebase_admin import credentials
    
    if os.path.exists(FIREBASE_CREDENTIALS_PATH):
        cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
        firebase_admin.initialize_app(cred)
        print("✅ Firebase Admin SDK initialized successfully")
    else:
        print("⚠️ Firebase credentials file not found. Push notifications will be disabled.")
        print(f"   Expected path: {FIREBASE_CREDENTIALS_PATH}")
except Exception as e:
    print(f"⚠️ Error initializing Firebase: {e}")
    print("   Push notifications will be disabled.")


# ==========================================
# EMAIL CONFIGURATION (Para notificaciones)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'SmartSales <noreply@smartsales.com>')

# URL del frontend (para links en emails)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3039')
