# Generated by Django 5.2.7 on 2025-11-10 23:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_add_advanced_sentiment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la oferta', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada')),
                ('offer_type', models.CharField(choices=[('FLASH_SALE', 'Venta Flash'), ('DAILY_DEAL', 'Oferta del Día'), ('SEASONAL', 'Oferta de Temporada'), ('CLEARANCE', 'Liquidación'), ('PERSONALIZED', 'Oferta Personalizada')], max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(help_text='Fecha y hora de inicio')),
                ('end_date', models.DateTimeField(help_text='Fecha y hora de fin')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Número máximo de usos (null = ilimitado)', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Usos máximos por usuario')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo de compra requerido', max_digits=10, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Mayor prioridad = se muestra primero')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('conversions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='Usuario específico para ofertas personalizadas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento específico para este producto (override)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_products', to='offers.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='products.product')),
            ],
            options={
                'verbose_name': 'Producto en Oferta',
                'verbose_name_plural': 'Productos en Oferta',
                'ordering': ['display_order', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Probabilidad de conversión (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reason', models.JSONField(default=dict, help_text='Factores que influyeron en la recomendación')),
                ('was_shown', models.BooleanField(default=False)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('was_clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('was_converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='offers.offer')),
                ('product', models.ForeignKey(blank=True, help_text='Producto recomendado dentro de la oferta', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendación de Oferta',
                'verbose_name_plural': 'Recomendaciones de Ofertas',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOfferInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEWED', 'Vista'), ('CLICKED', 'Click'), ('ADDED_TO_CART', 'Agregado al Carrito'), ('USED', 'Usada en Compra'), ('DISMISSED', 'Descartada'), ('EXPIRED', 'Expiró sin usar')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='offers.offer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción de Usuario con Oferta',
                'verbose_name_plural': 'Interacciones de Usuarios con Ofertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='offers_offe_status_be4d69_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type', 'status'], name='offers_offe_offer_t_f8179c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['target_user', 'status'], name='offers_offe_target__2fcbe1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerproduct',
            unique_together={('offer', 'product')},
        ),
        migrations.AddIndex(
            model_name='offerrecommendation',
            index=models.Index(fields=['user', 'score'], name='offers_offe_user_id_bc1c97_idx'),
        ),
        migrations.AddIndex(
            model_name='offerrecommendation',
            index=models.Index(fields=['was_converted', 'score'], name='offers_offe_was_con_99d001_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferinteraction',
            index=models.Index(fields=['user', 'offer', 'action'], name='offers_user_user_id_641f88_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferinteraction',
            index=models.Index(fields=['offer', 'action', 'created_at'], name='offers_user_offer_i_5636b3_idx'),
        ),
    ]
