# Generated by Django 5.2.7 on 2025-11-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado a este item (0-100)', max_digits=5, verbose_name='Porcentaje de Descuento'),
        ),
    ]
