# Generated by Django 5.2.7 on 2025-11-10 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_in_app', models.BooleanField(default=True, verbose_name='Pedidos (In-App)')),
                ('orders_push', models.BooleanField(default=True, verbose_name='Pedidos (Push)')),
                ('orders_email', models.BooleanField(default=True, verbose_name='Pedidos (Email)')),
                ('offers_in_app', models.BooleanField(default=True, verbose_name='Ofertas (In-App)')),
                ('offers_push', models.BooleanField(default=True, verbose_name='Ofertas (Push)')),
                ('offers_email', models.BooleanField(default=False, verbose_name='Ofertas (Email)')),
                ('system_in_app', models.BooleanField(default=True, verbose_name='Sistema (In-App)')),
                ('system_push', models.BooleanField(default=False, verbose_name='Sistema (Push)')),
                ('system_email', models.BooleanField(default=False, verbose_name='Sistema (Email)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token FCM del dispositivo', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='WEB', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='Nombre descriptivo del dispositivo (ej: Chrome en Windows)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Dispositivo',
                'verbose_name_plural': 'Tokens de Dispositivos',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ORDER_CONFIRMED', 'Pedido Confirmado'), ('ORDER_SHIPPED', 'Pedido Enviado'), ('ORDER_DELIVERED', 'Pedido Entregado'), ('PAYMENT_SUCCESS', 'Pago Exitoso'), ('PAYMENT_FAILED', 'Pago Fallido'), ('NEW_OFFER', 'Nueva Oferta Disponible'), ('OFFER_EXPIRING', 'Oferta Por Vencer'), ('STOCK_AVAILABLE', 'Producto Disponible'), ('SYSTEM_ALERT', 'Alerta del Sistema')], max_length=50)),
                ('channel', models.CharField(choices=[('IN_APP', 'En la App'), ('PUSH', 'Push Notification'), ('EMAIL', 'Correo Electrónico')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji o nombre de icon', max_length=50)),
                ('data', models.JSONField(blank=True, help_text='Datos adicionales para la notificación', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL de destino al hacer click', max_length=500)),
                ('action_text', models.CharField(blank=True, default='Ver Detalles', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx')],
            },
        ),
    ]
