# Generated by Django 5.2.7 on 2025-11-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_created_at_to_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, default='Ver Detalles', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL de destino al hacer click', max_length=500, null=True),
        ),
    ]
