# Generated by Django 5.0.6 on 2025-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='warranty_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estándar de la garantía para esta marca en meses (ej: 12 para 1 año).', null=True, verbose_name='Duración de Garantía (meses)'),
        ),
    ]
