# Generated by Django 5.2.7 on 2025-10-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_created_at_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], db_index=True, max_length=10, null=True, verbose_name='Sentimiento'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Puntuación compuesta VADER (-1 a 1)', null=True, verbose_name='Puntuación de Sentimiento'),
        ),
    ]
