# Generated by Django 5.2.7 on 2025-11-08 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review_sentiment_review_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aspect_delivery',
            field=models.PositiveIntegerField(blank=True, help_text='Evaluación de la experiencia de entrega (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Aspecto: Experiencia de Entrega'),
        ),
        migrations.AddField(
            model_name='review',
            name='aspect_quality',
            field=models.PositiveIntegerField(blank=True, help_text='Evaluación de calidad del producto (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Aspecto: Calidad del Producto'),
        ),
        migrations.AddField(
            model_name='review',
            name='aspect_value',
            field=models.PositiveIntegerField(blank=True, help_text='Evaluación de relación precio-calidad (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Aspecto: Relación Precio-Valor'),
        ),
        migrations.AddField(
            model_name='review',
            name='keywords',
            field=models.JSONField(blank=True, help_text='Palabras clave extraídas del comentario por IA', null=True, verbose_name='Palabras Clave'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, help_text='Nivel de confianza del análisis de sentimiento (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianza del Análisis'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_summary',
            field=models.CharField(blank=True, help_text='Breve resumen del sentimiento analizado por IA', max_length=200, null=True, verbose_name='Resumen del Sentimiento'),
        ),
    ]
